/**
 * @file tkl_memory.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 * 
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 * 
 */

// --- BEGIN: user defines and implements ---
#include "tkl_memory.h"
#include "tuya_error_code.h"
#include "osal/osal.h"
#include "tkl_output.h"
// --- END: user defines and implements ---

/**
 * @brief Alloc memory of system
 *
 * @param[in] size: memory size
 *
 * @note This API is used to alloc memory of system.
 *
 * @return the memory address malloced
 */
void *tkl_system_malloc(size_t size)
{
	void* ptr = OS_Malloc(size);
    if(NULL == ptr) {
        tkl_log_output("tkl_system_malloc failed, size(%d)!\r\n", size);
    }

    if (size > 4096) {
        tkl_log_output("tkl_system_malloc big memory, size(%d)!\r\n", size);
    }

    return ptr;
}

/**
 * @brief Free memory of system
 *
 * @param[in] ptr: memory point
 *
 * @note This API is used to free memory of system.
 *
 * @return void
 */
void tkl_system_free(void *ptr)
{
    if(ptr == NULL){
        return;
    }
        
    OS_Free(ptr);
}

/**
 * @brief Allocate and clear the memory
 *
 * @param[in]       nitems      the numbers of memory block
 * @param[in]       size        the size of the memory block
 *
 * @return the memory address calloced
 */
void *tkl_system_calloc(size_t nitems, size_t size)
{
    void *p = NULL;

    if (nitems == 0 || size == 0){
        return NULL;
    }
        
    if (size && nitems > (~(size_t)0) / size){
        return NULL;
    }
        
    p = OS_Malloc(nitems * size);
    if (p){
        memset(p, 0, nitems * size);
    }
        
    return p;
}

/**
 * @brief Re-allocate the memory
 *
 * @param[in]       nitems      source memory address
 * @param[in]       size        the size after re-allocate
 *
 * @return void
 */
void *tkl_system_realloc(void *ptr, size_t size)
{
    return pvPortReAlloc(ptr, size);
}

/**
 * @brief Get system free heap size
 *
 * @param none
 *
 * @return heap size
 */
int tkl_system_get_free_heap_size(void)
{
    return OS_GetFreeHeapSize();
}

