/**
 * @file tkl_pinmux.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "tkl_pinmux.h"
#include "tuya_error_code.h"
// --- END: user defines and implements ---

/**
 * @brief tuya multiple io pinmux func
 * @param[in] cfg: pin cfg array
 * @param[in] num: num of pin cfg array
 * 
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_multi_io_pinmux_config(TUYA_MUL_PIN_CFG_T *cfg, uint16_t num)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief tuya io pin to port,
 * @brief
 * @param[in] pin: pin number
 * @param[in] pin: pin type
 * @return Pin Function : Port and Channel,err < 0.
 * @return        16        8       8
 * @return[out] | rsv   |  port | channel |
 */
int32_t tkl_io_pin_to_func(uint32_t pin, TUYA_PIN_TYPE_E pin_type)
{
    switch (pin_type)
    {
        case TUYA_IO_TYPE_PWM:
            {
                int32_t tkl_pwm_io_pin_to_port(uint32_t pin);
                return tkl_pwm_io_pin_to_port(pin);
            }
        default:
            break;
    }
    return -1;
}

