/**
 * @file tkl_system.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 * 
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 * 
 */

// --- BEGIN: user defines and implements ---
#include "tkl_system.h"
#include "tuya_error_code.h"
#include "osal/osal.h"
#include "hal/hal_trng.h"
#include "hal/hal_wdt.h"
#include "reboot_trace/reboot_trace.h"
// --- END: user defines and implements ---

uint32_t tkl_system_enter_critical(void)
{
    uint32_t irq_mask = 0;
    irq_mask = portSET_INTERRUPT_MASK_FROM_ISR();

    return irq_mask;
}

void tkl_system_exit_critical(uint32_t irq_mask)
{
    portCLEAR_INTERRUPT_MASK_FROM_ISR(irq_mask);
    return;
}

/**
 * @brief system reset
 *
 * @param none
 *
 * @return none
 */
void tkl_system_reset(void)
{
    ln_chip_reboot();
    return;
}

/**
 * @brief Get system tick count
 *
 * @param none
 *
 * @return system tick count
 */
SYS_TICK_T tkl_system_get_tick_count(void)
{
    return (SYS_TICK_T)xTaskGetTickCount();
}

/**
 * @brief Get system millisecond
 *
 * @param none
 *
 * @return system millisecond
 */
SYS_TIME_T tkl_system_get_millisecond(void)
{
    return (SYS_TIME_T)(tkl_system_get_tick_count() * portTICK_RATE_MS);
}

/**
 * @brief Get system random data
 *
 * @param[in] range: random from 0  to range
 *
 * @return random value
 */
int tkl_system_get_random(uint32_t range)
{
    unsigned int trngNumber = 0;
    unsigned int random_num[4];

    if (0 == hal_trng_get_en_status(TRNG_BASE))
    {
        trng_init_t_def trng_init;
        memset(&trng_init, 0, sizeof(trng_init));
        trng_init.trng_fast_mode_en_status = TRNG_FAST_MODE_DIS;
        trng_init.trng_gap = 10;

        hal_trng_init(TRNG_BASE, &trng_init);
        hal_trng_en(TRNG_BASE, HAL_ENABLE);
    }

    while(hal_trng_get_en_status(TRNG_BASE) == 1);
    while(hal_trng_get_it_flag(TRNG_BASE,TRNG_IT_FLAG_TRNG_DONE) == 0)

    random_num[0] = hal_trng_get_data_0_31(TRNG_BASE);
    random_num[1] = hal_trng_get_data_32_63(TRNG_BASE);
    random_num[2] = hal_trng_get_data_64_95(TRNG_BASE);
    random_num[3] = hal_trng_get_data_96_127(TRNG_BASE);

    if (range >= 96)
    {
        return random_num[3] % range;
    }
    else if (range >= 64)
    {
        return random_num[2] % range;
    }
    else if (range >= 32)
    {
        return random_num[1] % range;
    }

    return random_num[0] % range;
}

/**
 * @brief Get system reset reason
 *
 * @param[in] describe: point to reset reason describe
 *
 * @return reset reason
 */
TUYA_RESET_REASON_E tkl_system_get_reset_reason(char **describe)
{
    TUYA_RESET_REASON_E reason;
    chip_reboot_cause_t cause;
    cause = ln_chip_get_reboot_cause();
    switch (cause)
    {
        case CHIP_REBOOT_POWER_ON:
            reason = TUYA_RESET_REASON_POWERON;
            break;
        case CHIP_REBOOT_SOFTWARE:
            reason = TUYA_RESET_REASON_SOFTWARE;
            break;
        case CHIP_REBOOT_WATCHDOG:
            reason = TUYA_RESET_REASON_HW_WDOG;
            break;
        default:
            reason = TUYA_RESET_REASON_UNSUPPORT;
            break;
    }
    return reason;
}

/**
 * @brief  system sleep
 *
 * @param[in] describe: num ms
 *
 * @return none
 */
void tkl_system_sleep(uint32_t num_ms)
{
    OS_MsDelay(num_ms);
}

/**
 * @brief system delay
 *
 * @param[in] msTime: time in MS
 *
 * @note This API is used for system sleep.
 *
 * @return void
 */
void tkl_system_delay(uint32_t num_ms)
{
    OS_MsDelay(num_ms);
}

/**
 * @brief get system cpu info
 *
 * @param[in] cpu_ary: info of cpus
 * @param[in] cpu_cnt: num of cpu
 * @note This API is used for system cpu info get.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */

OPERATE_RET tkl_system_get_cpu_info(TUYA_CPU_INFO_T **cpu_ary, int *cpu_cnt)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

