/**
 * @file tkl_output.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 * 
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 * 
 */

// --- BEGIN: user defines and implements ---
#include <stdio.h>
#include "tkl_output.h"
#include "tuya_error_code.h"
#include "log.h"
#include "osal/osal.h"
#include <stdarg.h>
#include "utils/debug/log.h"
// --- END: user defines and implements ---

/**
 * @brief Output log information
 *
 * @param[in] format: log information
 *
 * @note This API is used for outputing log information
 *
 * @return
 */
void tkl_log_output(const char *format, ...)
{
    va_list args;
    va_start(args, format);
    __sprintf(NULL, log_stdio_write, format, args);
    va_end(args);
    return 0;
}

/**
 * @brief Close log port
 *
 * @param void
 *
 * @note This API is used for closing log port.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_log_close(void)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief Open log port
 *
 * @param void
 *
 * @note This API is used for openning log port.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_log_open(void)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

