/**
 * @file tkl_mutex.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 * 
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 * 
 */

// --- BEGIN: user defines and implements ---
#include "tkl_mutex.h"
#include "osal/osal.h"
#include "log.h"
#include "tuya_error_code.h"
// --- END: user defines and implements ---

/**
 * @brief Create mutex
 *
 * @param[out] pMutexHandle: mutex handle
 *
 * @note This API is used to create and init a recursive mutex.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_mutex_create_init(TKL_MUTEX_HANDLE *pMutexHandle)
{
    if(!pMutexHandle){
        return OPRT_INVALID_PARM;
    }
        

#if configUSE_RECURSIVE_MUTEXES
    *pMutexHandle = (TKL_MUTEX_HANDLE)xSemaphoreCreateRecursiveMutex();
#else
    *pMutexHandle = (TKL_MUTEX_HANDLE)xSemaphoreCreateMutex();
#endif

    if (NULL == *pMutexHandle) {
        LOG(LOG_LVL_ERROR, "Mutex create failed\r\n");
        return OPRT_OS_ADAPTER_MUTEX_CREAT_FAILED;
    }

    return OPRT_OK;
}

/**
 * @brief Lock mutex
 *
 * @param[in] mutexHandle: mutex handle
 *
 * @note This API is used to lock a recursive mutex.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_mutex_lock(const TKL_MUTEX_HANDLE mutexHandle)
{
    if(!mutexHandle) {
        return OPRT_OS_ADAPTER_INVALID_PARM;
    }

    BaseType_t ret;
#if configUSE_RECURSIVE_MUTEXES
    ret = xSemaphoreTakeRecursive(mutexHandle, portMAX_DELAY);
#else
    ret = xSemaphoreCreateMutex(mutexHandle, portMAX_DELAY);
#endif
    if (ret != pdTRUE) {
        return OPRT_OS_ADAPTER_MUTEX_LOCK_FAILED;
    }

    return OPRT_OK;
}

/**
 * @brief Try Lock mutex
 *
 * @param[in] mutexHandle: mutex handle
 *
 * @note This API is used to try lock a recursive mutex.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_mutex_trylock(const TKL_MUTEX_HANDLE mutexHandle)
{
    if(!mutexHandle) {
        return OPRT_OS_ADAPTER_INVALID_PARM;
    }

    BaseType_t ret;
#if configUSE_RECURSIVE_MUTEXES
    ret = xSemaphoreTakeRecursive(mutexHandle, 0);
#else
    ret = xSemaphoreCreateMutex(mutexHandle, 0);
#endif
    if (ret != pdTRUE) {
        return OPRT_OS_ADAPTER_MUTEX_LOCK_FAILED;
    }

    return OPRT_OK;
}

/**
 * @brief Unlock mutex
 *
 * @param[in] mutexHandle: mutex handle
 *
 * @note This API is used to unlock a recursive mutex.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_mutex_unlock(const TKL_MUTEX_HANDLE mutexHandle)
{
    if(!mutexHandle) {
        return OPRT_OS_ADAPTER_INVALID_PARM;
    }

    BaseType_t ret;
#if defined(configUSE_RECURSIVE_MUTEXES)
    ret = xSemaphoreGiveRecursive(mutexHandle);
#else
    ret = xSemaphoreGive(mutexHandle);
#endif
    if (pdTRUE != ret) {
        return OPRT_OS_ADAPTER_MUTEX_UNLOCK_FAILED;
    }

    return OPRT_OK;
}

/**
 * @brief Release mutex
 *
 * @param[in] mutexHandle: mutex handle
 *
 * @note This API is used to release a recursive mutex.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_mutex_release(const TKL_MUTEX_HANDLE mutexHandle)
{
    if(!mutexHandle) {
        return OPRT_OS_ADAPTER_INVALID_PARM;
    }

    vSemaphoreDelete(mutexHandle);

    return OPRT_OK;
}

