/**
 * @file tkl_spi.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 * 
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 * 
 */

// --- BEGIN: user defines and implements ---
#include "tkl_spi.h"
#include "tuya_error_code.h"
#include "osal/osal.h"
#include "hal/hal_gpio.h"
#include "hal/hal_spi.h"
// --- END: user defines and implements ---

#define SPI_NUM_MAX     1
#define SPI_TIMEOUT     (1000000UL)

typedef struct  {
    TUYA_SPI_NUM_E tuya_spi_id;
    uint32_t sck_base;
    gpio_pin_t sck_pin;
    uint32_t mosi_base;
    gpio_pin_t mosi_pin;
    uint32_t miso_base;
    gpio_pin_t miso_pin;
    uint32_t cs_base;
    gpio_pin_t cs_pin;
}TUYA_LN_SPI_CNV_S;

#define GET_SCK_BASE(port) tuya_ln_spi_map[port].sck_base
#define GET_SCK_PIN(port) tuya_ln_spi_map[port].sck_pin

#define GET_MOSI_BASE(port) tuya_ln_spi_map[port].mosi_base
#define GET_MOSI_PIN(port) tuya_ln_spi_map[port].mosi_pin

#define GET_MISO_BASE(port) tuya_ln_spi_map[port].miso_base
#define GET_MISO_PIN(port) tuya_ln_spi_map[port].miso_pin

#define GET_CS_BASE(port) tuya_ln_spi_map[port].cs_base
#define GET_CS_PIN(port) tuya_ln_spi_map[port].cs_pin

static TUYA_LN_SPI_CNV_S tuya_ln_spi_map[] = {
    {TUYA_SPI_NUM_0, GPIOA_BASE, GPIO_PIN_5, GPIOA_BASE, GPIO_PIN_6, GPIOB_BASE, GPIO_PIN_6, GPIOB_BASE, GPIO_PIN_7},
};

/**
 * @brief spi init
 *
 * @param[in] port: spi port
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_spi_init(TUYA_SPI_NUM_E port, const TUYA_SPI_BASE_CFG_T *cfg)
{
    if (port>=SPI_NUM_MAX || NULL==cfg) {
        return OPRT_INVALID_PARM;
    }

    /* sck */
    hal_gpio_pin_afio_en(GET_SCK_BASE(port), GET_SCK_PIN(port), HAL_DISABLE);
    hal_gpio_pin_afio_select(GET_SCK_BASE(port), GET_SCK_PIN(port), SPI0_CLK);
    hal_gpio_pin_afio_en(GET_SCK_BASE(port), GET_SCK_PIN(port), HAL_ENABLE);
    /* MOSI */
    hal_gpio_pin_afio_en(GET_MOSI_BASE(port), GET_MOSI_PIN(port), HAL_DISABLE);
    hal_gpio_pin_afio_select(GET_MOSI_BASE(port), GET_MOSI_PIN(port), SPI0_MOSI);
    hal_gpio_pin_afio_en(GET_MOSI_BASE(port), GET_MOSI_PIN(port), HAL_ENABLE);
    /* MISO */
    hal_gpio_pin_afio_en(GET_MISO_BASE(port), GET_MISO_PIN(port), HAL_DISABLE);
    hal_gpio_pin_afio_select(GET_MISO_BASE(port), GET_MISO_PIN(port), SPI0_MISO);
    hal_gpio_pin_afio_en(GET_MISO_BASE(port), GET_MISO_PIN(port), HAL_ENABLE);


    spi_init_type_def spi_init_cfg;
    memset(&spi_init_cfg, 0, sizeof(spi_init_cfg));

    hal_spi_en(SPI0_BASE,HAL_DISABLE);

    if (cfg->role == TUYA_SPI_ROLE_MASTER) {
        spi_init_cfg.spi_mode = SPI_MODE_MASTER;
    }

    switch (cfg->mode) {
        case TUYA_SPI_MODE0:
            spi_init_cfg.spi_cpol = SPI_CPOL_LOW;
            spi_init_cfg.spi_cpha = SPI_CPHA_1EDGE;
        break;
        case TUYA_SPI_MODE1:
            spi_init_cfg.spi_cpol = SPI_CPOL_LOW;
            spi_init_cfg.spi_cpha = SPI_CPHA_2EDGE;
        break;
        case TUYA_SPI_MODE2:
            spi_init_cfg.spi_cpol = SPI_CPOL_HIGH;
            spi_init_cfg.spi_cpha = SPI_CPHA_1EDGE;
        break;
        case TUYA_SPI_MODE3:
            spi_init_cfg.spi_cpol = SPI_CPOL_HIGH;
            spi_init_cfg.spi_cpha = SPI_CPHA_2EDGE;
        break;
        default: break;
    }

    if (cfg->type == TUYA_SPI_AUTO_TYPE) {
        spi_init_cfg.spi_nss_mode = SPI_NSS_HARD;
        /* cs */
        hal_gpio_pin_afio_en(GET_CS_BASE(port), GET_CS_PIN(port), HAL_DISABLE);
        hal_gpio_pin_afio_select(GET_CS_BASE(port), GET_CS_PIN(port), SPI0_CSN);
        hal_gpio_pin_afio_en(GET_CS_BASE(port), GET_CS_PIN(port), HAL_ENABLE);
    } else if (cfg->type == TUYA_SPI_SOFT_TYPE) {
        spi_init_cfg.spi_nss_mode = SPI_NSS_SOFT;
    } else {
        ;
    }

    if (cfg->databits == TUYA_SPI_DATA_BIT8) {
        spi_init_cfg.spi_data_size = SPI_DATASIZE_8B;
    } else {
        spi_init_cfg.spi_data_size = SPI_DATASIZE_16B;
    }

    if (cfg->bitorder == TUYA_SPI_ORDER_MSB2LSB) {
        spi_init_cfg.spi_first_bit = SPI_FIRST_BIT_MSB;
    } else {
        spi_init_cfg.spi_first_bit = SPI_FIRST_BIT_LSB;
    }

    spi_init_cfg.spi_baud_rate_prescaler = SPI_BAUDRATEPRESCALER_256;

    hal_spi_init(SPI0_BASE, &spi_init_cfg);
    hal_spi_en(SPI0_BASE,HAL_ENABLE);
    hal_spi_ssoe_en(SPI0_BASE,HAL_DISABLE);

    return OPRT_OK;
}

/**
 * @brief spi deinit
 *
 * @param[in] port: spi port
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_spi_deinit(TUYA_SPI_NUM_E port)
{
    if (port>=SPI_NUM_MAX) {
        return OPRT_INVALID_PARM;
    }
    hal_spi_en(SPI0_BASE,HAL_DISABLE);
    hal_spi_deinit(SPI0_BASE);

    return OPRT_OK;
}

/**
 * Spi send
 *
 * @param[in]  port      the spi device
 * @param[in]  data     spi send data
 * @param[in]  size     spi send data size
 *
 * @return  OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_spi_send(TUYA_SPI_NUM_E port, void *data, uint16_t size)
{
    uint16_t *send_data = data;
    uint16_t send_count = 0;
    if (port>=SPI_NUM_MAX || NULL==data) {
        return OPRT_INVALID_PARM;
    }

    for (send_count=0; send_count<size; send_count++) {
        hal_spi_wait_bus_idle(SPI0_BASE, SPI_TIMEOUT);
        if(hal_spi_wait_txe(SPI0_BASE, SPI_TIMEOUT) == 1) {
            hal_spi_send_data(SPI0_BASE, send_data[send_count]);
        }
    }

    return OPRT_OK;
}

/**
 * spi_recv
 *
 * @param[in]   port      the spi device
 * @param[out]  data     spi recv data
 * @param[in]   size     spi recv data size
 *
 * @return  OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_spi_recv(TUYA_SPI_NUM_E port, void *data, uint16_t size)
{
    uint16_t *recv_data = data;
    uint16_t recv_count = 0;
    if (port>=SPI_NUM_MAX || NULL==data) {
        return OPRT_INVALID_PARM;
    }

    for (recv_count=0; recv_count<size; recv_count++) {
        hal_spi_wait_bus_idle(SPI0_BASE, SPI_TIMEOUT);
        if(hal_spi_wait_rxne(SPI0_BASE, SPI_TIMEOUT) == 1) {
            recv_data[recv_count] = hal_spi_recv_data(SPI0_BASE);
        }
    }

    return OPRT_OK;
}

/**
 * @brief spi transfer
 *
 * @param[in] port: spi port
 * @param[in] send_buf: spi send buf
 * @param[out] send_buf:spi recv buf
 * @param[in] length: spi msg length
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_spi_transfer(TUYA_SPI_NUM_E port, void *send_buf, void *receive_buf, uint32_t length)
{
    OPERATE_RET op_ret = OPRT_OK;

    return op_ret;
}

/**
 * @brief spi transfer
 *
 * @param[in] port: spi port
 * @param[in] send_buf: spi send buf
 * @param[in] send_len: send_len
 * @param[out] receive_buf:spi recv buf
 * @param[in] receive_len: receive_len
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_spi_transfer_with_length(TUYA_SPI_NUM_E port, void *send_buf, uint32_t send_len, void *receive_buf,
                                         uint32_t receive_len)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief adort spi transfer,or spi send, or spi recv
 *
 * @param[in] port: spi port
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */

OPERATE_RET tkl_spi_abort_transfer(TUYA_SPI_NUM_E port)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief get spi status.
 *
 * @param[in] port: spi port
 * @param[out]  TUYA_SPI_STATUS_T,please refer to tuya_cloud_types.h
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_spi_get_status(TUYA_SPI_NUM_E port, TUYA_SPI_STATUS_T *status)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief spi irq init
 * NOTE: call this API will not enable interrupt
 *
 * @param[in] port: spi port, id index starts at 0
 * @param[in] cb:  spi irq cb
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_spi_irq_init(TUYA_SPI_NUM_E port, TUYA_SPI_IRQ_CB cb)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief spi irq enable
 *
 * @param[in] port: spi port id, id index starts at 0
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_spi_irq_enable(TUYA_SPI_NUM_E port)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief spi irq disable
 *
 * @param[in] port: spi port id, id index starts at 0
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_spi_irq_disable(TUYA_SPI_NUM_E port)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief spi transferred data count.
 *
 * @param[in] port: spi port id, id index starts at 0
 *
 * @return >=0,number of currently transferred data items. <0,err.
 * during  tkl_spi_send, tkl_spi_recv and tkl_spi_transfer operation.
 */
int32_t tkl_spi_get_data_count(TUYA_SPI_NUM_E port)
{
    // --- BEGIN: user implements ---
    return 0;
    // --- END: user implements ---
}

/**
 * @brief spi ioctl
 *
 * @param[in]       cmd     user def
 * @param[in]       args    args associated with the command
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_spi_ioctl(TUYA_SPI_NUM_E port, uint32_t cmd, void *args)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

