/**
 * @file tkl_watchdog.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 * 
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 * 
 */

// --- BEGIN: user defines and implements ---
#include "tkl_watchdog.h"
#include "tuya_error_code.h"
#include "osal/osal.h"
#include "hal/hal_wdt.h"
// --- END: user defines and implements ---

/**
 * @brief watchdog init
 *
 * @param[in] cfg: watchdog config
 *
 * @return 0, init error; >0 : the actually watchdog interval
 */
uint32_t tkl_watchdog_init(TUYA_WDOG_BASE_CFG_T *cfg)
{
    uint16_t i=0;
    uint32_t shift_left_num = 3;
    uint16_t wdt_top_value = 0;
    if (NULL == cfg) {
        return 0;
    }

    LOG(LOG_LVL_INFO, "----- %s\r\n", __func__);

    for (i=0; i<16; i++) {
        if (((1<<shift_left_num)-1) >= cfg->interval_ms) {
            break;
        }
        shift_left_num++;
    }
    if (shift_left_num <= 18) {
        wdt_top_value = shift_left_num-3;
    } else {
        wdt_top_value = 15;
    }

    LOG(LOG_LVL_INFO, "wdg shift_left_num:0x%x, set num:%d, top:0x%02x\r\n", shift_left_num, (1<<(wdt_top_value+3))-1, wdt_top_value);

    wdt_init_t_def wdt_init;
    memset(&wdt_init,0,sizeof(wdt_init));
    wdt_init.wdt_rmod = WDT_RMOD_0;
    wdt_init.wdt_rpl = WDT_RPL_32_PCLK;
    wdt_init.top = wdt_top_value;
	
    hal_wdt_init(WDT_BASE, &wdt_init);

    hal_wdt_en(WDT_BASE,HAL_ENABLE);
    hal_wdt_cnt_restart(WDT_BASE);
    return ((1<<(wdt_top_value+3))-1);
}

/**
 * @brief watchdog deinit
 *
 * @param[in] none
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_watchdog_deinit(void)
{
    hal_wdt_deinit();
    hal_wdt_en(WDT_BASE, HAL_DISABLE);
    return OPRT_OK;
}

/**
 * @brief refresh watch dog
 *
 * @param[in] none
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_watchdog_refresh(void)
{
    hal_wdt_cnt_restart(WDT_BASE);
    return OPRT_OK;
}

